# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-18 15:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_slug', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('language', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='PodcastItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('audio_url', models.URLField()),
                ('audio_length', models.PositiveIntegerField()),
                ('audio_type', models.CharField(choices=[('audio/mpeg', 'audio/mpeg')], max_length=15)),
                ('duration', models.DurationField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='podcast.Podcast')),
            ],
            options={
                'verbose_name': 'PodcastItem',
                'verbose_name_plural': 'PodcastItems',
            },
        ),
        migrations.CreateModel(
            name='PodcastScraping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.URLField()),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
            ],
            options={
                'verbose_name': 'PodcastScraping',
                'verbose_name_plural': 'PodcastScraping',
            },
        ),
    ]
