# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 10:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20160618_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastScrapingConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('start_url', models.URLField()),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
            ],
            options={
                'verbose_name': 'Podcast scraping configuration',
                'verbose_name_plural': 'Podcast scraping configurations',
            },
        ),
        migrations.CreateModel(
            name='PodcastScrapingSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('steps', django.contrib.postgres.fields.jsonb.JSONField()),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast')),
            ],
            options={
                'verbose_name': 'Podcast scraping steps',
                'verbose_name_plural': 'Podcast scraping steps',
            },
        ),
        migrations.RemoveField(
            model_name='podcastscraping',
            name='podcast',
        ),
        migrations.AlterModelOptions(
            name='podcastitem',
            options={'verbose_name': 'Podcast item', 'verbose_name_plural': 'Podcast items'},
        ),
        migrations.DeleteModel(
            name='PodcastScraping',
        ),
        migrations.AddField(
            model_name='podcastscrapingconfiguration',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcast.PodcastScrapingSteps'),
        ),
    ]
