# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0003_auto_20160619_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastscrapingsteps',
            name='podcast',
        ),
    ]
