# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20160626_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podcast.PodcastScrapingConfiguration'),
        ),
    ]
