# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_auto_20160626_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 26, 19, 59, 25, 490937, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
