# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_auto_20160629_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastitem',
            name='audio_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
