# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_auto_20160629_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
