# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0012_auto_20160629_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastitem',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
