# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0013_auto_20160630_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastIgnoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore_items', to='podcast.Podcast')),
            ],
            options={
                'verbose_name_plural': 'Podcast ignore items',
                'verbose_name': 'Podcast ignore item',
            },
        ),
        migrations.AlterUniqueTogether(
            name='podcastignoreitem',
            unique_together=set([('podcast', 'link')]),
        ),
    ]
