# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0014_auto_20160630_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastitem',
            options={'ordering': ('-pub_date', 'pk'), 'verbose_name': 'Podcast item', 'verbose_name_plural': 'Podcast items'},
        ),
        migrations.AlterField(
            model_name='podcastitem',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 3, 19, 33, 24, 54656, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
