# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0017_auto_20160706_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastscrapingconfiguration',
            name='last_scrap',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
