# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0018_podcastscrapingconfiguration_last_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
