# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0021_podcastignoreitem_ignore_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastitem',
            name='scrap_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
