# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 19:55
from __future__ import unicode_literals

from django.db import migrations


def scrap_date(apps, schema_editor):
    PodcastItem = apps.get_model('podcast', 'PodcastItem')
    for item in PodcastItem.objects.all():
        item.scrap_date = item.pub_date
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0022_podcastitem_scrap_date'),
    ]

    operations = [
        migrations.RunPython(scrap_date, lambda *a, **k: None),
    ]
