# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0023_auto_20170825_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastitem',
            name='scrap_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
